procmail/urls.py
# ⁻*- coding: utf-8 -*-
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License version 3 for
# more details.
#
# You should have received a copy of the GNU General Public License version 3
# along with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# (c) 2015 Valentin Samir
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name="index"),
    url(r'^(?P<id>([0-9.]*))$', views.index, name="index"),
    url(r'^download$', views.download, name="download"),
    url(r'^delete/(?P<id>([0-9.]+))/(?P<view_name>([^/]+))$', views.delete, name="delete"),
    url(
        r'^delete/(?P<id>([0-9.]+))/(?P<view_name>([^/]+))/(?P<curr_id>([0-9.]*))$',
        views.delete,
        name="delete"
    ),
    url(r'^edit/(?P<id>([0-9.]*))$', views.edit, name="edit"),
    url(r'^edit_simple/(?P<id>([0-9.]*))$', views.edit_simple, name="edit_simple"),
    url(
        r'^move/(?P<old_id>([0-9.]+))/(?P<new_id>([0-9.]+))/(?P<curr_id>([0-9.]*))$',
        views.move,
        name="move"
    ),
    url(r'^up/(?P<id>([0-9.]+))/(?P<cur_id>([0-9.]*))$', views.up, name="up"),
    url(r'^down/(?P<id>([0-9.]+))/(?P<cur_id>([0-9.]*))$', views.down, name="down"),
    url(
        r'^create/(?P<id>([0-9.]*))$',
        login_required(views.CreateStatement.as_view()),
        name="create"
    ),
    url(r'^reverse$', views.reverse_view, name="reverse"),
)

procmail/forms.py
# ⁻*- coding: utf-8 -*-
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License version 3 for
# more details.
#
# You should have received a copy of the GNU General Public License version 3
# along with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# (c) 2015 Valentin Samir
from django import forms
from django.forms.formsets import BaseFormSet, formset_factory
from django.utils.translation import ugettext_lazy as _

import re
import collections

import utils
import forms_initial
import forms_utils
from pyprocmail import procmail


forms.Field.set_extra = forms_utils.set_extra
forms.Field.extra = {}


class DeleteStatement(forms.Form):
    def __init__(self, *args, **kwargs):
        self.statement = kwargs.pop('statement', None)
        super(DeleteStatement, self).__init__(*args, **kwargs)


class MetaForm(forms.Form):
    def __init__(self, *args, **kwargs):
        statement = kwargs.pop('statement', None)
        if statement is not None:
            kwargs['initial'] = forms_initial.meta_form(statement)
        super(MetaForm, self).__init__(*args, **kwargs)

    title = forms.CharField(label=_('title'), max_length=100)
    comment = forms.CharField(label=_('comment'), max_length=256, required=False)


class SimpleConditionKind(forms.Form):
    kind = forms.ChoiceField(
        label='',
        widget=forms.RadioSelect,
        choices=[
            ("and", _("matching every rules below")),
            ("or", _("matching any rules below")),
            ("all", _("all mails")),
        ]
    )


class SimpleCondition(forms.Form):

    conditions = None

    object = forms.ChoiceField(
        label=_('Scope'),
        choices=[
            ("", ""),
            ("Subject", _("Subject")),
            ("From", _("From")),
            ("To", _("To")),
            ("custom_header", "..."),
            ("headers", _("headers")),
            ("body", _("body")),
            ("headers_body", _("headers and body")),
        ],
        required=False
    )

    custom_header = forms.CharField(
        label=_('Custom header'), max_length=256, required=False
        ).set_extra(show_if_selected=("object", ["custom_header"]))

    match = forms.ChoiceField(
        label=_('Match'),
        choices=[
            ("", ""),
            ("contain", _("contain")),
            ("not_contain", _("does not contain")),
            ("equal", _("is equal to")),
            ("not_equal", _("is differant than")),
            ("exists", _("exists")),
            ("not_exists", _("does not exists")),
            ("regex", _("match the regular expression")),
            ("not_regex", _("do not match the regular expression")),
            ("size_g", _("size strictly greater than")),
            ("size_l", _("size strictly lower than")),
        ],
        required=False
    )

    param = forms.CharField(
        label=_('Parameter'), max_length=256, required=False
    ).set_extra(
        show_if_selected=(
            'match',
            [
                "contain", "not_contain", "equal", "not_equal",
                "regex", "not_regex", "size_g", "size_l"
            ]
        )
    )

    def clean_custom_header(self):
        if ':' in self.cleaned_data["custom_header"]:
            raise forms.ValidationError(_("A header name cannot contain ':'"))
        return self.cleaned_data["custom_header"].strip()

    def clean(self):
        data = self.cleaned_data
        if not data.get("match") or data.get('DELETE', False):
            return
        if data['object'] == "custom_header" and not data["custom_header"]:
            raise forms.ValidationError(_("Please specify a custom header"))
        if data["match"] not in ["exists", "not_exists"] and not data["param"]:
            raise forms.ValidationError(_("Please specify a parameter"))
        if data["match"] in ["size_g", "size_l"]:
            try:
                data["param"] = int(data["param"].strip())
            except ValueError:
                raise forms.validationError(_("Parameter must be a whole number of byte"))
        if data["match"] in ["regex", "not_regex"]:
            try:
                re.compile(data["param"])
            except re.error as error:
                raise forms.validationError(_("Bad regular expression : %s") % error)

        flags = {}
        if data["object"] == "body":
            flags['B'] = True
        elif data["object"] == "headers_body":
            flags['H'] = True
            flags['B'] = True
        else:
            flags['H'] = True
        flags = flags.keys()
        flags.sort()
        self.flags = tuple(flags)

        if data["object"] == "Subject":
            prefix = "^Subject:[ ]*"
        elif data["object"] == "From":
            prefix = "^From:[ ]*"
        elif data["object"] == "To":
            prefix = "^To:[ ]*"
        elif data["object"] == "custom_header":
            prefix = "^%s:[ ]*" % utils.escape_re(data["custom_header"])
        else:
            prefix = ""

        if data["match"] in [
            "contain", "not_contain", "equal", "not_equal",
            "exists", "not_exists", "regex", "not_regex"
        ]:
            if data["match"].startswith("not_"):
                negate = True
                match = data["match"][4:]
            else:
                negate = False
                match = data["match"]
            if data["match"] == "contain":
                regex = "%s.*%s.*" % (prefix, utils.escape_re(data["param"]))
            elif match == "equal":
                regex = "%s%s$" % (prefix, utils.escape_re(data["param"]))
            elif match == "exists":
                regex = "%s.*" % prefix
            elif match == "regex":
                regex = "%s%s" % (prefix, data["param"])
            condition = procmail.ConditionRegex(regex)
            if negate:
                condition = procmail.ConditionNegate(condition)
            self.conditions = [condition]
        elif data["match"] in ["size_g", "size_l"]:
            if data["match"] == "size_g":
                sign = '>'
            else:
                sign = '<'
            if prefix:
                condition1 = procmail.ConditionRegex("%s[ ]*\/.*" % prefix)
                condition2 = procmail.ConditionVariable(
                    "MATCH",
                    procmail.ConditionSize(sign, data["param"])
                )
                self.conditions = [condition1, condition2]
            else:
                condition = procmail.ConditionSize(sign, data["param"])
                self.conditions = [condition]
        else:
            raise forms.ValidationError(_("Should not happening, contact an administrator 1"))


class SimpleConditionBaseSet(forms_utils.ExtraSet):
    def clean(self):
        conditions = collections.defaultdict(list)
        for form in self.forms:
            if form.errors:
                return
            if form.conditions is not None:
                conditions[form.flags].extend(form.conditions)
        self.conditions = conditions.items()


SimpleConditionSet = formset_factory(
    SimpleCondition,
    extra=1,
    formset=SimpleConditionBaseSet,
    can_delete=True
)


class SimpleAction(forms.Form):
    statement = None

    action = forms.ChoiceField(
        label=_('Action'),
        choices=[
            ("", ""),
            ("save", _("Save mail in")),
            ("copy", _("Copy mail in")),
            ("redirect", _("Redirect mail to")),
            ("redirect_copy", _("Send a copy to")),
            ("delete", _("Delete mail")),
            ("variable", _("Define a variable")),
        ]
    )

    param = forms.CharField(
        label=_('Parameter'), max_length=256, required=False
    ).set_extra(show_if_selected=("action", ["save", "copy", "redirect", "redirect_copy"]))
    variable_name = forms.CharField(
        label=_('Variable name'), max_length=256, required=False
    ).set_extra(show_if_selected=("action", ["variable"]))
    variable_value = forms.CharField(
        label=_('Variable value'), max_length=256, required=False
    ).set_extra(show_if_selected=("action", ["variable"]))

    def clean(self):
        data = self.cleaned_data
        if not data['action'] or data.get('DELETE', False):
            return
        if data['action'] in ["save", "copy", "redirect", "redirect_copy"] and not data['param']:
            raise forms.ValidationError(_("Please specify a %s") % self.param.label)
        if data['action'] == "variable" and not data["variable_name"]:
            raise forms.ValidationError(_("Please specify a %s") % self.variable_name.label)

        if data['action'] == "save":
            header = procmail.Header(lockfile=True)
            action = procmail.ActionSave(data['param'])
            self.statement = procmail.Recipe(header, action)
        elif data['action'] == "copy":
            header = procmail.Header(lockfile=True)
            header.c = True
            action = procmail.ActionSave(data['param'])
            self.statement = procmail.Recipe(header, action)
        elif data['action'] == "redirect":
            header = procmail.Header()
            action = procmail.ActionForward([data['param']])
            self.statement = procmail.Recipe(header, action)
        elif data['action'] == "redirect_copy":
            header = procmail.Header()
            header.c = 1
            action = procmail.ActionForward([data['param']])
            self.statement = procmail.Recipe(header, action)
        elif data['action'] == "delete":
            header = procmail.Header()
            action = procmail.ActionSave("/dev/null")
            self.statement = procmail.Recipe(header, action)
        elif data['action'] == "variable":

procmail/templates/procmail/base.html
{% load i18n %}
{% load staticfiles %}
<html>
<head>
  {% for href in PROCMAIL_VENDOR_CSS.values %}<link rel="stylesheet" href="{{href}}">
  {% endfor %}
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  {% for src in PRCOMAIL_VENDOR_JAVASCRIPT.values %}<script src="{{src}}"></script>
  {% endfor %}
  <script src="{% static "procmail/functions.js" %}"></script>
  {% include "procmail/javascript.html" %}
  <link rel="stylesheet" href="{% static "procmail/styles.css" %}">
  <link rel="stylesheet" href="{% static "procmail/tree.css" %}">
  </head>
  <body>
    <div class="container-fluid">
      <table>
        <tr>
          {% if procmailrc != None %}
            <td tyle="vertical-align:top">
              <div id="procmailrc">
                <h1><a href="{% url "procmail:index" %}">ProcmailRc</a></h1>
                {% include "procmail/list.html" with procmailrc=procmailrc %}
              </div>
            </td>
          {% endif %}
          <td style="vertical-align:top">
            <div id="main" class="container">
              <div class="row">
                <div class="col-md-1 col-xs-0 col-sm-0"></div>
                <div class="col-md-10 col-xs-12 col-sm-12">
                  {% if PROCMAIL_INPLACE == False %}
                    <br/>
                    <div class="alert alert-warning" role="alert">
                      <i class="fa fa-exclamation-triangle fa-lg"></i>
                      {% blocktrans with directory=PROCMAIL_DEBUG_DIR %}
                        Currently in debug mode. This application de not edit your real procmailrc but a copy
                        made in the {{directory}} directory.
                      {% endblocktrans %}
                    </div>
                  {% endif %}
                  {% block content %}
                  {% endblock %}
                </div>
                <div class="col-md-1 col-xs-0 col-sm-0"></div>
              </div>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </body>
</html>

procmail/templates/procmail/create.html
{% extends "procmail/base.html" %}
{% load i18n %}
{% block content %}
  {{ wizard.form.media }}
  <p>{% trans "Step" %} {{ wizard.steps.step1 }} {% trans "of" %} {{ wizard.steps.count }}</p>
  <button
    class="btn btn-primary"
    type="button"
    data-toggle="collapse"
    data-target=".advanced_params"
   >
    {% trans "Show Advanced parameters" %}
  </button>
  <br/>
  <br/>
  <form action="" method="post">
    {% csrf_token %}
    {{ wizard.management_form }}
    {% include "procmail/form.html" with form=wizard.form %}
    {% if wizard.steps.prev %}
      <button
        name="wizard_goto_step"
        type="submit"
        value="{{ wizard.steps.first }}"
        class="btn btn-secondary"
      >
        {% trans "first step" %}
      </button>
      <button
        name="wizard_goto_step"
        type="submit"
        value="{{ wizard.steps.prev }}"
        class="btn btn-secondary"
      >
        {% trans "prev step" %}
      </button>
    {% endif %}
    <input type="submit" value="{% trans "submit" %}" class="btn btn-primary"/>
  </form>
{% endblock %}

procmail/templates/procmail/delete.html
{% extends "procmail/base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Delete statement" %}</h1>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">{% trans "Deletion of a procmail rule" %}</h3>
    </div>
    <div class="panel-body">
      <p>
        {% blocktrans with type=type title=title %}
          Are you sure you want to delete the {{type}} "{{title}}" ?
        {% endblocktrans %}
      </p>
    </div>
    <div class="panel-footer text-right">
      <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="{% trans "Delete" %}" class="btn btn-danger"/>
        {% with "procmail:"|add:view_name as view_name %}
          <a class="btn btn-default keep_scroll_list" href="{% url view_name curr_stmt.id %}" />
            {% trans "Cancel"%}
          </a>
        {% endwith %}
      </form>
   </div>
  </div>
{% endblock %}

procmail/templates/procmail/edit.html
{% extends "procmail/base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Advanced editor" %}</h1>
  {% if curr_stmt.django.is_simple %}
    <a href="{% url "procmail:edit_simple" curr_stmt.id %}" class="btn btn-primary keep_scroll_list">
      {% trans "Go to the simple edition page" %}
    </a>
  {%  endif %}
  <form action="" method="post">
    {% csrf_token %}
    <h2>{% trans "Metadata" %}</h2>
    {% include "procmail/form.html" with form=form_meta %}
    <button
      class="btn btn-primary"
      type="button"
      data-toggle="collapse"
      data-target=".advanced_params"
    >
      {% trans "Show Advanced parameters" %}
    </button>

    {% if curr_stmt.is_recipe %}
      <h2>{% trans "Recipe" %}</h2>
      <h3>{% trans "Header" %}</h3>
      {% include "procmail/form.html" with form=form_header %}

      <h3>{% trans "Conditions" %}</h3>
      {% include "procmail/form.html" with form=form_condition %}

      <h3>{% trans "Action" %}<h3>
      {{form_action.show_init}}
      {% if form_action.non_field_errors %}
        {{form_action.non_field_errors}}
      {% endif %}
      <table class="table table-striped table-bordered table-nonfluid">
        <tr>
          <td style="white-space: nowrap;">
            {{form_action.action_type.label_tag}}
          </td>
          <td style="width:100%">
            {{ form_action.action_type.errors }}
            {{ form_action.action_type }}
            {{ form_action.action_type.help_text}}
          </td>
        </tr>
        <tr id="action_param">
          <td>
            {{form_action.action_param.label_tag}}
          </td>
          <td>
            {{ form_action.action_param.errors }}
            {{ form_action.action_param }}
            {{ form_action.action_param.help_text}}
          </td>
        </tr>
        {% if curr_stmt.action.is_nested %}
          {% for stmt in curr_stmt %}
            {% if not stmt.is_comment %}
              <tr>
                <td colspan="2">
                  <a href="{% url "procmail:edit" stmt.id %}">
                   {% if stmt.meta_title %}{{stmt.meta_title}}{% else %}{{stmt.gen_title}}{% endif %}
                  </a>
                </td>
              </tr>
            {% endif %}
          {% endfor %}
        {% endif %}
        <tr id="action_nested">
          <td colspan="2" style="text-align:center">
            <input
              type="submit"
              name="action_add"
              value="{% trans "Add actions" %}"
              class="btn btn-primary btn-lg"
            />
          </td>
        </tr>
      <table>
      <script>
      var hide_param = function() {
       var value = $('#id_action-action_type').val();
       if(value == "nested"){
         $('#action_param').hide();
         $('#action_nested').show();
       } else {
         $('#action_param').show();
         $('#action_nested').hide();
       }
      };

      $('#id_action-action_type').change(hide_param);
      $('#id_action-action_type').ready(hide_param);
      </script>

    {% elif curr_stmt.is_assignment %}
      <h2>Assignement</h2>
      {% include "procmail/form.html" with form=form_assignment %}
    {% endif %}

    <input type="submit" value="{% trans "Submit" %}" class="btn btn-primary"/>
    <input type="submit" value="{% trans "Delete" %}" name="delete_stmt" class="btn btn-danger" style="float:right"/>
  </form>

  <h2>{% trans "Preview" %}</h2>
  <pre>{{curr_stmt.render}}</pre>
{% endblock %}

procmail/templates/procmail/edit_simple.html
{% extends "procmail/base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Simple editor" %}</h1>
  <form action="" method="post">
    {% csrf_token %}
    <h2>{% trans "Metadata" %}</h2>
    {% include "procmail/form.html" with form=form_meta %}
    <h2>{% trans "Conditions" %}</h2>
    {% include "procmail/form.html" with form=form_cond_kind %}
    {% include "procmail/form.html" with form=form_cond table_id="conditions_table" %}
    <h2>{% trans "Actions" %}</h2>
    {% include "procmail/form.html" with form=form_action %}

    <div style="white-space: nowrap;">
        <div style="display: inline-block;width:33%;">
            <input type="submit" value="{% trans "Submit" %}" class="btn btn-primary"/>
        </div>
        <div style="display: inline-block;width:34%;text-align:center;">
            <a href="{% url "procmail:edit" curr_stmt.id %}" class="btn btn-warning keep_scroll_list">
              {% trans "Go to advanced edition page" %}
            </a>
        </div>
        <div style="display: inline-block;width:33%;text-align:right;">
            <input 
              type="submit"
              value="{% trans "Delete" %}"
              name="delete_stmt"
              class="btn btn-danger"
            />
        <div>
    </div>
  </form>
  <p class="text-center">
    
  </p>
<script>
$(document).ready(function() {
    var show_conditions = function() {
        if(this.checked){
            if (this.value == 'all')
                $('#conditions_table').hide()
            else
                $('#conditions_table').show()
        }
    }
    $('input[type=radio][name={{form_cond_kind.kind.html_name}}]').each(show_conditions);
    $('input[type=radio][name={{form_cond_kind.kind.html_name}}]').change(show_conditions);
});

</script>
{% endblock %}

procmail/templates/procmail/form.html
{{ form.media }}
{% if form.non_field_errors %}
  {{form.non_field_errors}}
{% endif %}
{% if form.forms and form.non_form_errors %}
  {{form.non_form_errors}}
{% endif %}
<table
  class="table table-striped table-bordered table-nonfluid"
  {% if table_id %} id="{{table_id}}"{% endif %}
 >
  {{form.show_init}}
  {% if form.forms %}
    {{ form.management_form }}
      <tr>
        {% for field in form.0 %}
          <th {% if field.field.show == False %}class="collapse advanced_params"{% endif %}>
            {{field.label}}{% if field.help_text %}
            <span title="{{ field.help_text}}" class="icon_help">
              <i class="fa fa-question"></i>
            </span>{% endif %}
          </th>
        {% endfor %}
      </tr>
      {% for form in form %}
        {% if form.non_field_errors %}
          <tr><td colspan="30">{{form.non_field_errors}}</td></tr>
        {% endif %}
        <tr>
          {% for field in form %}
            <td {% if field.field.show == False %}class="collapse advanced_params"{% endif %}>
              {{field.errors}} {{field}}
            </td>
          {% endfor %}
        </tr>
      {% endfor %}

  {% else %}
    {% for field in form %}
      <tr {% if field.field.show == False %}class="collapse advanced_params"{% endif %}>
        {% if field.label %}<td>{{field.label_tag}}</td>{% endif%}
        <td{% if not field.label %} colspan="2"{% endif%}>
          {{ field.errors }} {{ field }} {{ field.help_text}}
        </td>
      </tr>
    {% endfor %}
  {% endif %}
</table>


{% spaceless %}
{% if form.forms %}
  {% for f in form %}
    {% include "procmail/form_javascript.html" with form=f %}
  {% endfor %}
{% else %}
  {% include "procmail/form_javascript.html" with form=form %}
{% endif %}
{% endspaceless %}

procmail/templates/procmail/form_javascript.html
{% for field in form %}
  {% if field.field.extra.show_if_selected %}
    {% with field.field.extra.show_if_selected.0 as select %}
      <script>
        var show_function = function (){
          var show = false;
          {% for value in field.field.extra.show_if_selected.1 %}
            if($('#{{select.auto_id}}').val() == '{{value}}')
              show = true;
          {% endfor %}
          if(show)
            $('#{{field.auto_id}}').show()
          else
            $('#{{field.auto_id}}').hide()
        };
        $(document).ready(show_function);
        $('#{{select.auto_id}}').change(show_function);
      </script>
    {% endwith %}
  {% endif %}
  {% if field.field.extra.show_if_checked %}
    {% with field.field.extra.show_if_checked as checkbox %}
      <script>
        var show_function = function() {
          if($('#{{checkbox.auto_id}}')[0].checked)
            $('#{{field.auto_id}}').show()
          else
            $('#{{field.auto_id}}').hide()
        };
        $(document).ready(show_function);
        $('#{{checkbox.auto_id}}').change(show_function);
      </script>
    {% endwith %}
  {% endif %}
{% endfor %}

procmail/templates/procmail/index.html
{% extends "procmail/base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "ProcmailRC Manager" %}</h1>
 
  <h2>{% trans "Generated procmailrc" %}
      <a href="{% url "procmail:download" %}" class="btn btn-primary">
        {% trans "Download" %}
      </a>
  </h2>
  <pre style="overflow: inherit;">{{procmailrc.render}}</pre>
{% endblock %}}

procmail/templates/procmail/javascript.html
<script>
    function reverse(view_name, args, kwargs){
        return $.ajax(
            "{% url "procmail:reverse" %}",
            {   
                method: "POST",
                data: {view_name:view_name, args:JSON.stringify(args), kwargs:JSON.stringify(kwargs)}
            }
        );
    }
    var curr_id = "{{curr_stmt.id}}";
  </script>

procmail/templates/procmail/list.html
{% load i18n %}
{% load staticfiles %}
<div class="tree">
<ul class="sortable" data-id="" data-parent_id="" id="main_list">
  {% for stmt in procmailrc.django.flat %}{% spaceless %}
    {% if stmt == "in_list" %}{% spaceless %}
      {% if not stmt.data.in_simple or not simple %}
        <ul
          class="sortable"
          {% for key, value in stmt.data.items %}
          data-{{key}}="{{value}}"{% endfor %}
        >
      {% endif %}
    {% endspaceless %}{% elif stmt == "out_list" %}{% spaceless %}
      {% if not stmt.data.in_simple or not simple %}
      </ul>
      {% endif %}
    {% endspaceless %}{% elif stmt == "in_item" %}{% spaceless %}
      {% if not stmt.data.in_simple or not simple %}
      <li
        class="{% if not stmt.data.display %}hide{% endif %}"
        {% for key, value in stmt.data.items %}
        data-{{key}}="{{value}}"{% endfor %}
      >
      {% endif %}
    {% endspaceless %}{% elif stmt == "out_item" %}{% spaceless %}
      {% if not stmt.data.in_simple or not simple %}
      </li>
      {% endif %}
    {% endspaceless %}{% elif not simple or not stmt.django.in_simple %}
      <div style="white-space: nowrap;">
        <div style="display:inline-block;width:100%">
        {% if not stmt.is_first %}
          <a href="{% url "procmail:up" stmt.id curr_stmt.id%}" class="up_down">
            <i title="move up" class="fa fa-caret-up"></i>
          </a>
        {% endif %}
        {% if not stmt.is_last %}
          <a href="{% url "procmail:down" stmt.id curr_stmt.id%}" class="up_down">
            <i title="move down" class="fa fa-caret-down"></i>
          </a>
        {% endif %}
        {% if stmt.id != curr_stmt.id %}
          <a  href="{% spaceless %}
              {% if simple and stmt.django.is_simple %}
                {% url "procmail:edit_simple" stmt.id %}
              {% else %}
                {% url "procmail:edit" stmt.id %}
              {% endif %}{% endspaceless %}"
              class="keep_scroll_list"
          >
        {% endif %}{% spaceless %}
          <span> {% spaceless %}
            {% if stmt.meta_title %}
              {{stmt.meta_title}}
            {% else %}
              {{stmt.gen_title}}
            {% endif %}
          {% endspaceless %}</span>
        {% endspaceless %}{% if stmt.id != curr_stmt.id %}</a>{% endif %}
        </div>
        <div style="display:inline-block;text-align:right" class="delete_list_item">
            <a
                class="delete_list_item keep_scroll_list"
                href="{% url "procmail:delete" stmt.id current_url_name curr_stmt.id %}"
                title="{% trans "Delete" %}"
            >
                <i class="fa fa-times" class="delete_list_item"></i>
            </a>
        </div>
      </div>
    {% endif %}
  {% endspaceless %}{% endfor %}
</ul>
<a href="{% url "procmail:create" "" %}" class="btn btn-primary btn-block add_rule">
    {% trans "Add a rule" %}
</a>
<br/>
</div>
<script>

var sortables = []
$( ".sortable" ).each(
    function() {
        var id = $(this).data("id");
        var sortable = Sortable.create(
            this,
            {
                group: "procmailrc",
                pull: true,
                put: true,
                onUpdate: function (evt) {
                    if(evt.oldIndex != evt.newIndex){
                        var parent_id = $(evt.item).data("parent_id");
                        var old_id = get_id(parent_id, evt.oldIndex);
                        var new_id = get_id(parent_id, evt.newIndex);
                        do_move("{{current_view_name}}", curr_id, old_id, new_id);
                    }
                },
                onAdd: function (/**Event*/evt) {
                    var old_id = get_id($(evt.from).data("id"), evt.oldIndex);
                    var new_id = get_id(id, evt.newIndex);
                    do_move("{{current_view_name}}", curr_id, old_id, new_id);
                },
                onStart: function (/**Event*/evt) {
                    var item = $('li[data-id="'+ get_id(id, evt.oldIndex) +'"]');
                    item.find("ul").first().css("display", "none");
                },
                onEnd: function (/**Event*/evt) {
                    var item = $('li[data-id="'+ get_id(id, evt.oldIndex) +'"]');
                    item.find("ul").first().css("display", "block");
                }
            }
        );
        sortables.push(sortable);
    }
);
</script>
<script src="{% static "procmail/list.js" %}"></script>

procmail/templates/procmail/parse_error.html
{% extends "procmail/base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Syntax error in procmailrc" %}</h1>
  <div class="alert alert-danger" role="alert">
    {% blocktrans with line=line lineno=lineno col=col%}
      Fail to parse your procmailrc. You probably have a syntax error
      near {{line}} at line {{lineno}}, column {{col}}.
    {% endblocktrans %}
  </div>
{% endblock %}}